dinbento/dinbento/config/routes.rb
Rails.application.routes.draw do
  resources :orders

  get '/search_orders', to: 'orders#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root 'orders#index'

end

dinbento/dinbento/app/models/concerns/user.rb
class User < ActiveRecord::Base
  has_secure_password validation: false
end

dinbento/dinbento/app/models/order.rb
class Order < ActiveRecord::Base
  validates :name, presence: true
  validates :name, length: { minimum:2 }

  validates :phone, presence: true
  validates :phone, length: { minimum:9 }
  validates :phone, uniqueness: true

  validates :description, presence: true
end

# skinny controller, fat model

dinbento/dinbento/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

dinbento/dinbento/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :phone, :description)
    end
end

dinbento/dinbento/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #登入頁面使用
  end

  def create


    #尋找使用者
    user = User.find_by(name: params[:name])   
    #驗證使用者，若成功，就建立一個 session，把 user_id 放入 session hash
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    #登出畫面使用，刪除 session hash 裡面的 user_id
    session[:user_id] = nil
    # redirect_to root_path
    redirect_to login_path
  end
end

dinbento/dinbento/app/helpers/application_helper.rb
module ApplicationHelper
end

dinbento/dinbento/app/helpers/orders_helper.rb
module OrdersHelper
end

dinbento/dinbento/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "訂便當", orders_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li><%= link_to '新增訂單', new_order_path %></li>
        <li><%= link_to '登出', logout_path %></li>
        <% else %>
        <li><%= link_to '登入', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

dinbento/dinbento/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinbento</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>
<%= yield %>

</body>
</html>

dinbento/dinbento/app/views/orders/_form.html.erb
<div class="well col-sm-6">
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit((@order.new_record?) ? "New Order" : "Edit order", class: ' btn btn-danger')%>
  </div>
<% end %>
</div>

dinbento/dinbento/app/views/orders/edit.html.erb
<!-- <h1>Editing Order</h1> -->
<%= render 'shared/title', title: 'Editing Order'%>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', search_orders_path %>

dinbento/dinbento/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Listing Orders</h1> -->
<%= render 'shared/title', title: 'Listing Orders'%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.phone %></td>
        <td><%= order.description %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- <a href="/orders/new">New Order</a> -->

dinbento/dinbento/app/views/orders/new.html.erb
<!-- <h1>New Order</h1> -->
<%= render 'shared/title', title: 'New Order'%>

<%= render 'form' %>

<%= link_to 'Back', search_orders_path %>

dinbento/dinbento/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @order.description %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', search_orders_path %>

dinbento/dinbento/app/views/shared/_title.html.erb
<h1><%= title %></h1>
<hr>